In [ ]:
import pandas as pd

In [3]:
df=pd.read_csv("../data/raw/Fitbit_dataset.csv")

In [4]:
df.head()

,Unnamed: 0,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI,Base_MET,HR_Intensity,Effective_MET,Calories_Burned (kcal)
0,0,56,Female,53.8,1.62,163,149,71,1.01,HIIT,22.1,3.5,3,1,20.4,9.5,0.847826,8.054348,437.7
1,1,46,Male,54.9,1.75,170,126,73,0.25,Yoga,19.9,3.4,3,0,18.0,3.0,0.546392,1.639175,22.5
2,2,32,Female,68.5,1.61,190,171,60,0.33,HIIT,20.4,2.7,3,1,26.5,9.5,0.853846,8.111538,183.4
3,3,25,Male,98.8,1.86,189,135,69,0.78,Yoga,30.3,4.4,3,0,28.5,3.0,0.550000,1.650000,127.2
4,4,38,Male,95.5,1.71,176,138,66,0.55,Cardio,23.7,2.2,2,0,32.5,7.0,0.654545,4.581818,240.7

In [5]:
df=df.drop(columns=['Unnamed: 0'])

In [6]:
df.head()

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI,Base_MET,HR_Intensity,Effective_MET,Calories_Burned (kcal)
0,56,Female,53.8,1.62,163,149,71,1.01,HIIT,22.1,3.5,3,1,20.4,9.5,0.847826,8.054348,437.7
1,46,Male,54.9,1.75,170,126,73,0.25,Yoga,19.9,3.4,3,0,18.0,3.0,0.546392,1.639175,22.5
2,32,Female,68.5,1.61,190,171,60,0.33,HIIT,20.4,2.7,3,1,26.5,9.5,0.853846,8.111538,183.4
3,25,Male,98.8,1.86,189,135,69,0.78,Yoga,30.3,4.4,3,0,28.5,3.0,0.550000,1.650000,127.2
4,38,Male,95.5,1.71,176,138,66,0.55,Cardio,23.7,2.2,2,0,32.5,7.0,0.654545,4.581818,240.7

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14102 entries, 0 to 14101
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            14102 non-null  int64
 1   Gender                         14102 non-null  object
 2   Weight (kg)                    14102 non-null  float64
 3   Height (m)                     14102 non-null  float64
 4   Max_BPM                        14102 non-null  int64
 5   Avg_BPM                        14102 non-null  int64
 6   Resting_BPM                    14102 non-null  int64
 7   Session_Duration (hours)       14102 non-null  float64
 8   Workout_Type                   14102 non-null  object
 9   Fat_Percentage                 14102 non-null  float64
 10  Water_Intake (liters)          14102 non-null  float64
 11  Workout_Frequency (days/week)  14102 non-null  int64
 12  Experience_Level               14102 non-null  int64
 13  BMI                            14102 non-null  float64
 14  Base_MET                       14102 non-null  float64
 15  HR_Intensity                   14102 non-null  float64
 16  Effective_MET                  14102 non-null  float64
 17  Calories_Burned (kcal)         14102 non-null  float64
dtypes: float64(10), int64(6), object(2)
memory usage: 1.9+ MB

In [8]:
df.rename(columns={
    'Age': 'Age',
    'Gender': 'Gender',
    'Weight (kg)': 'Weight_kg',
    'Height (m)': 'Height_m',
    'Max_BPM': 'Max_BPM',
    'Avg_BPM': 'Avg_BPM',
    'Resting_BPM': 'Resting_BPM',
    'Session_Duration (hours)': 'Session_Duration_hours',
    'Workout_Type': 'Workout_Type',
    'Fat_Percentage': 'Fat_Percentage',
    'Water_Intake (liters)': 'Water_Intake_liters',
    'Workout_Frequency (days/week)': 'Workout_Frequency_days_per_week',
    'Experience_Level': 'Experience_Level',
    'BMI': 'BMI',
    'Base_MET': 'Base_MET',
    'HR_Intensity': 'HR_Intensity',
    'Effective_MET': 'Effective_MET',
    'Calories_Burned (kcal)': 'Calories_Burned_kcal'
}, inplace=True)

In [9]:
df['Gender']

0        Female
1          Male
2        Female
3          Male
4          Male
          ...
14097      Male
14098      Male
14099    Female
14100      Male
14101    Female
Name: Gender, Length: 14102, dtype: object

In [10]:
df['Gender'].value_counts()

Gender
Male      7122
Female    6980
Name: count, dtype: int64

In [11]:
df['Gender'].dtype

dtype('O')

In [12]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [13]:
df.isnull().sum()

Age                                0
Gender                             0
Weight_kg                          0
Height_m                           0
Max_BPM                            0
Avg_BPM                            0
Resting_BPM                        0
Session_Duration_hours             0
Workout_Type                       0
Fat_Percentage                     0
Water_Intake_liters                0
Workout_Frequency_days_per_week    0
Experience_Level                   0
BMI                                0
Base_MET                           0
HR_Intensity                       0
Effective_MET                      0
Calories_Burned_kcal               0
dtype: int64

In [14]:
df['Workout_Type']

0            HIIT
1            Yoga
2            HIIT
3            Yoga
4          Cardio
           ...
14097        Yoga
14098      Cardio
14099    Strength
14100        HIIT
14101      Cardio
Name: Workout_Type, Length: 14102, dtype: object

In [15]:
df['Workout_Type'].value_counts()

Workout_Type
HIIT        2898
Strength    2838
Mixed       2822
Cardio      2774
Yoga        2770
Name: count, dtype: int64

In [16]:
df['Workout_Type'].unique()

array(['HIIT', 'Yoga', 'Cardio', 'Mixed', 'Strength'], dtype=object)

In [17]:
df['Workout_Type'].nunique()

5

In [18]:
df['Workout_Type'].isnull().sum()

np.int64(0)

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.describe()

,Age,Weight_kg,Height_m,Max_BPM,Avg_BPM,Resting_BPM,Session_Duration_hours,Fat_Percentage,Water_Intake_liters,Workout_Frequency_days_per_week,Experience_Level,BMI,Base_MET,HR_Intensity,Effective_MET,Calories_Burned_kcal
count,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000,14102.000000
mean,38.528365,68.252922,1.680338,181.400794,147.955538,69.333073,0.830135,21.844313,3.598624,4.150262,1.150546,24.092838,6.726918,0.701554,4.924756,279.492866
std,12.007994,13.330332,0.097543,12.913603,14.628858,7.110206,0.288531,5.974424,0.626391,1.650013,1.057974,3.776271,2.180444,0.100263,2.124242,172.858430
min,18.000000,37.800000,1.450000,150.000000,109.000000,55.000000,0.250000,8.000000,1.500000,2.000000,0.000000,18.000000,3.000000,0.539474,1.618421,18.400000
25%,28.000000,58.400000,1.610000,171.000000,137.000000,64.000000,0.620000,17.700000,3.200000,3.000000,0.000000,21.200000,6.000000,0.648000,4.187500,143.200000
50%,39.000000,67.300000,1.680000,181.000000,147.000000,70.000000,0.820000,22.000000,3.600000,4.000000,1.000000,24.000000,7.000000,0.700000,4.550000,251.050000
75%,49.000000,77.000000,1.750000,192.000000,158.000000,75.000000,1.030000,26.100000,4.000000,5.000000,2.000000,26.700000,8.000000,0.752475,6.019802,373.700000
max,59.000000,125.100000,1.900000,205.000000,187.000000,85.000000,1.900000,40.000000,5.900000,7.000000,3.000000,35.000000,9.500000,0.860215,8.172043,1442.400000

In [21]:
numeric_columns=df.select_dtypes(include='number').columns

print(numeric_columns)

Index(['Age', 'Weight_kg', 'Height_m', 'Max_BPM', 'Avg_BPM', 'Resting_BPM',
       'Session_Duration_hours', 'Fat_Percentage', 'Water_Intake_liters',
       'Workout_Frequency_days_per_week', 'Experience_Level', 'BMI',
       'Base_MET', 'HR_Intensity', 'Effective_MET', 'Calories_Burned_kcal'],
      dtype='object')

In [22]:
numeric_columns.isnull().sum()

np.int64(0)

In [23]:
numeric_cols = df.select_dtypes(include='number').columns

for col in numeric_cols:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]
    
    print(f"{col}: {len(outliers)} outliers")

Age: 0 outliers
Weight_kg: 93 outliers
Height_m: 0 outliers
Max_BPM: 0 outliers
Avg_BPM: 0 outliers
Resting_BPM: 0 outliers
Session_Duration_hours: 31 outliers
Fat_Percentage: 10 outliers
Water_Intake_liters: 124 outliers
Workout_Frequency_days_per_week: 0 outliers
Experience_Level: 0 outliers
BMI: 39 outliers
Base_MET: 0 outliers
HR_Intensity: 0 outliers
Effective_MET: 0 outliers
Calories_Burned_kcal: 284 outliers

In [24]:
df['Age']

0        56
1        46
2        32
3        25
4        38
         ..
14097    18
14098    54
14099    23
14100    43
14101    19
Name: Age, Length: 14102, dtype: int64

In [25]:
df['Age'].between(18, 80).all()

np.True_

In [26]:
df['Height_m']

0        1.62
1        1.75
2        1.61
3        1.86
4        1.71
         ...
14097    1.76
14098    1.71
14099    1.52
14100    1.69
14101    1.60
Name: Height_m, Length: 14102, dtype: float64

In [27]:
df['Height_m'].describe()

count    14102.000000
mean         1.680338
std          0.097543
min          1.450000
25%          1.610000
50%          1.680000
75%          1.750000
max          1.900000
Name: Height_m, dtype: float64

In [28]:
df['Height_m'].isnull().sum()

np.int64(0)

In [29]:
df['Weight_kg']

0        53.8
1        54.9
2        68.5
3        98.8
4        95.5
         ...
14097    75.7
14098    66.4
14099    74.7
14100    70.8
14101    87.3
Name: Weight_kg, Length: 14102, dtype: float64

In [30]:
df['Weight_kg'].describe()

count    14102.000000
mean        68.252922
std         13.330332
min         37.800000
25%         58.400000
50%         67.300000
75%         77.000000
max        125.100000
Name: Weight_kg, dtype: float64

In [31]:
col = 'Weight_kg'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower) | (df[col] > upper)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
print("Number of Outliers:", len(outliers))

Q1: 58.4
Q3: 77.0
IQR: 18.6
Lower Bound: 30.499999999999996
Upper Bound: 104.9
Number of Outliers: 93

In [32]:
df['Max_BPM']

0        163
1        170
2        190
3        189
4        176
        ...
14097    205
14098    162
14099    204
14100    171
14101    205
Name: Max_BPM, Length: 14102, dtype: int64

In [33]:
df['Max_BPM'].describe()

count    14102.000000
mean       181.400794
std         12.913603
min        150.000000
25%        171.000000
50%        181.000000
75%        192.000000
max        205.000000
Name: Max_BPM, dtype: float64

In [34]:
df[['Age', 'Max_BPM']].sort_values('Max_BPM', ascending=False).head(20)

       Age  Max_BPM
14083   18      205
14073   23      205
20      19      205
14097   18      205
14      20      205
4033    27      205
4029    18      205
10999   22      205
11122   24      205
11118   21      205
11116   18      205
11022   22      205
12972   20      205
3878    18      205
3903    18      205
4255    18      205
3851    18      205
4394    21      205
3766    21      205
13026   19      205

In [35]:
df['Avg_BPM']

0        149
1        126
2        171
3        135
4        138
        ...
14097    143
14098    131
14099    161
14100    154
14101    156
Name: Avg_BPM, Length: 14102, dtype: int64

In [36]:
df['Avg_BPM'].describe()

count    14102.000000
mean       147.955538
std         14.628858
min        109.000000
25%        137.000000
50%        147.000000
75%        158.000000
max        187.000000
Name: Avg_BPM, dtype: float64

In [37]:
df['Avg_BPM'].isnull().sum()

np.int64(0)

In [38]:
df[['Age', 'Avg_BPM', 'Max_BPM']].sort_values(
    'Avg_BPM',
    ascending=False
).head(20)

       Age  Avg_BPM  Max_BPM
55      23      187      205
6544    22      187      205
3413    22      187      205
7372    19      187      205
6641    21      187      205
14      20      186      205
11820   24      186      204
6442    20      186      205
3679    18      186      205
902     19      186      205
9423    25      186      205
3359    18      186      205
1289    25      186      205
4479    22      186      205
11551   20      186      205
12816   19      186      205
1376    20      186      205
8640    18      186      205
6874    18      186      205
2991    23      186      205

In [39]:
df['Resting_BPM']

0        71
1        73
2        60
3        69
4        66
         ..
14097    67
14098    73
14099    61
14100    55
14101    64
Name: Resting_BPM, Length: 14102, dtype: int64

In [40]:
df['Resting_BPM'].describe()

count    14102.000000
mean        69.333073
std          7.110206
min         55.000000
25%         64.000000
50%         70.000000
75%         75.000000
max         85.000000
Name: Resting_BPM, dtype: float64

In [41]:
df['Resting_BPM'].isnull().sum()

np.int64(0)

In [42]:
df['Resting_BPM'].head()

0    71
1    73
2    60
3    69
4    66
Name: Resting_BPM, dtype: int64

In [43]:
df['Session_Duration_hours'].head()

0    1.01
1    0.25
2    0.33
3    0.78
4    0.55
Name: Session_Duration_hours, dtype: float64

In [44]:
df['Session_Duration_hours'].describe()

count    14102.000000
mean         0.830135
std          0.288531
min          0.250000
25%          0.620000
50%          0.820000
75%          1.030000
max          1.900000
Name: Session_Duration_hours, dtype: float64

In [45]:
col = 'Session_Duration_hours'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower) | (df[col] > upper)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
print("Number of Outliers:", len(outliers))

Q1: 0.62
Q3: 1.03
IQR: 0.41000000000000003
Lower Bound: 0.0050000000000000044
Upper Bound: 1.645
Number of Outliers: 31

In [46]:
df['Fat_Percentage'].head()

0    22.1
1    19.9
2    20.4
3    30.3
4    23.7
Name: Fat_Percentage, dtype: float64

In [47]:
df['Fat_Percentage'].describe()

count    14102.000000
mean        21.844313
std          5.974424
min          8.000000
25%         17.700000
50%         22.000000
75%         26.100000
max         40.000000
Name: Fat_Percentage, dtype: float64

In [48]:
col = 'Fat_Percentage'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower) | (df[col] > upper)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
print("Number of Outliers:", len(outliers))

Q1: 17.7
Q3: 26.1
IQR: 8.400000000000002
Lower Bound: 5.099999999999996
Upper Bound: 38.7
Number of Outliers: 10

In [49]:
df['Water_Intake_liters']

0        3.5
1        3.4
2        2.7
3        4.4
4        2.2
        ...
14097    3.7
14098    2.7
14099    4.3
14100    3.9
14101    3.7
Name: Water_Intake_liters, Length: 14102, dtype: float64

In [50]:
df['Water_Intake_liters'].describe()

count    14102.000000
mean         3.598624
std          0.626391
min          1.500000
25%          3.200000
50%          3.600000
75%          4.000000
max          5.900000
Name: Water_Intake_liters, dtype: float64

In [52]:
col = 'Water_Intake_liters'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower) | (df[col] > upper)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
print("Number of Outliers:", len(outliers))

Q1: 3.2
Q3: 4.0
IQR: 0.7999999999999998
Lower Bound: 2.0000000000000004
Upper Bound: 5.199999999999999
Number of Outliers: 124

In [53]:
df[
    (df['Water_Intake_liters'] < 2.0) |
    (df['Water_Intake_liters'] > 5.2)
][
    ['Age', 'Weight_kg', 'Session_Duration_hours',
     'Water_Intake_liters', 'Calories_Burned_kcal']
].sort_values(
    'Water_Intake_liters',
    ascending=False
)

,Age,Weight_kg,Session_Duration_hours,Water_Intake_liters,Calories_Burned_kcal
10826,29,75.4,1.53,5.9,688.6
2744,58,50.7,1.19,5.6,360.8
900,30,61.1,1.90,5.6,694.7
4938,38,81.1,1.36,5.6,661.8
7223,59,75.5,1.49,5.6,679.8
...,...,...,...,...,...
6476,53,66.3,0.25,1.7,75.9
12328,23,73.0,0.25,1.7,83.4
7419,28,77.3,0.48,1.7,167.6
5374,31,57.5,0.44,1.6,115.1
11406,44,68.7,0.51,1.5,158.4

In [54]:
df['Workout_Frequency_days_per_week']

0        3
1        3
2        3
3        3
4        2
        ..
14097    4
14098    3
14099    3
14100    7
14101    7
Name: Workout_Frequency_days_per_week, Length: 14102, dtype: int64

In [55]:
df['Workout_Frequency_days_per_week'].describe()

count    14102.000000
mean         4.150262
std          1.650013
min          2.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: Workout_Frequency_days_per_week, dtype: float64

In [56]:
df['Experience_Level']

0        1
1        0
2        1
3        0
4        0
        ..
14097    1
14098    1
14099    1
14100    3
14101    3
Name: Experience_Level, Length: 14102, dtype: int64

In [57]:
df['Experience_Level'].describe()

count    14102.000000
mean         1.150546
std          1.057974
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          3.000000
Name: Experience_Level, dtype: float64

In [58]:
df['BMI']

0        20.4
1        18.0
2        26.5
3        28.5
4        32.5
         ...
14097    24.3
14098    22.7
14099    32.5
14100    24.9
14101    34.2
Name: BMI, Length: 14102, dtype: float64

In [59]:
df['BMI'].describe()

count    14102.000000
mean        24.092838
std          3.776271
min         18.000000
25%         21.200000
50%         24.000000
75%         26.700000
max         35.000000
Name: BMI, dtype: float64

In [60]:
col = 'BMI'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower) | (df[col] > upper)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
print("Number of Outliers:", len(outliers))

Q1: 21.2
Q3: 26.7
IQR: 5.5
Lower Bound: 12.95
Upper Bound: 34.95
Number of Outliers: 39

In [61]:
df['Calories_Burned_kcal']

0        437.7
1         22.5
2        183.4
3        127.2
4        240.7
         ...
14097     77.5
14098    281.7
14099    310.3
14100    579.8
14101    386.8
Name: Calories_Burned_kcal, Length: 14102, dtype: float64

In [62]:
df['Calories_Burned_kcal'].describe()

count    14102.000000
mean       279.492866
std        172.858430
min         18.400000
25%        143.200000
50%        251.050000
75%        373.700000
max       1442.400000
Name: Calories_Burned_kcal, dtype: float64

In [ ]:
col = 'Calories_Burned (kcal)'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower) | (df[col] > upper)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
print("Number of Outliers:", len(outliers))

Q1: 143.2
Q3: 373.7
IQR: 230.5
Lower Bound: -202.55
Upper Bound: 719.45
Number of Outliers: 284

In [63]:
df[
    ['Workout_Frequency_days_per_week',
     'Session_Duration_hours',
     'Calories_Burned_kcal']
].head(20)

,Workout_Frequency_days_per_week,Session_Duration_hours,Calories_Burned_kcal
0,3,1.01,437.7
1,3,0.25,22.5
2,3,0.33,183.4
3,3,0.78,127.2
4,2,0.55,240.7
5,5,0.75,58.3
6,2,0.41,48.3
7,3,0.52,172.8
8,2,0.78,335.1
9,4,0.67,197.5
10,7,1.07,89.9
11,3,0.44,152.3
12,4,0.43,126.0
13,6,1.00,483.9
14,3,0.65,351.1
15,4,0.97,196.7
16,2,0.48,168.2
17,2,0.25,80.4
18,7,1.39,378.8
19,3,0.56,252.5

EDA

In [ ]:
numeric_cols = df.select_dtypes(include='number').columns

print(numeric_cols)

Index(['Age', 'Weight (kg)', 'Height (m)', 'Max_BPM', 'Avg_BPM', 'Resting_BPM',
       'Session_Duration (hours)', 'Fat_Percentage', 'Water_Intake (liters)',
       'Workout_Frequency (days/week)', 'Experience_Level', 'BMI', 'Base_MET',
       'HR_Intensity', 'Effective_MET', 'Calories_Burned (kcal)'],
      dtype='object')